// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FeatureSelect.Tests.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Defining features in config")]
    public partial class DefiningFeaturesInConfigFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "config-feature-source.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Defining features in config", "  In order to easily control which features are enabled\r\n  As a release manager\r\n" +
                    "  I want to use standard .NET configuration ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Loading config from a file")]
        public virtual void LoadingConfigFromAFile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Loading config from a file", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
  testRunner.Then("feature \"feature1\" is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
  testRunner.And("feature \"feature1b\" is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
  testRunner.And("feature \"feature2\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
  testRunner.And("feature \"feature2b\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
  testRunner.And("feature \"feature3\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
  testRunner.And("feature \"feature4\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
  testRunner.And("feature \"feature5\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
  testRunner.And("feature \"feature6\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
  testRunner.And("feature \"feature7\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
  testRunner.And("feature \"null-feature\" is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
  testRunner.And("feature \"unknown\" is unknown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can configure features based on config")]
        [NUnit.Framework.TestCaseAttribute("male 18-25", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("male 25-30", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("female 18-25", "disabled", null)]
        public virtual void CanConfigureFeaturesBasedOnConfig(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can configure features based on config", "  Feature \"feature3\" is enabled only if the cohort is \"male 18-25\"", exampleTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 24
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table1.AddRow(new string[] {
                        "cohort",
                        string.Format("{0}", value)});
#line 25
  testRunner.And("the context contains", ((string)(null)), table1, "And ");
#line 28
  testRunner.Then(string.Format("feature \"feature3\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Config based features can accept multiple values")]
        [NUnit.Framework.TestCaseAttribute("Abc", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Xyz", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("Ghi", "disabled", null)]
        public virtual void ConfigBasedFeaturesCanAcceptMultipleValues(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Config based features can accept multiple values", "  Feature \"feature4\" is enabled only if the company is \"Abc\" OR \"Xyz\"", exampleTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 40
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table2.AddRow(new string[] {
                        "company",
                        string.Format("{0}", value)});
#line 41
  testRunner.And("the context contains", ((string)(null)), table2, "And ");
#line 44
  testRunner.Then(string.Format("feature \"feature4\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Config based features can accept regular expressions")]
        [NUnit.Framework.TestCaseAttribute("abc", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("abcdef", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("xyz", "disabled", null)]
        public virtual void ConfigBasedFeaturesCanAcceptRegularExpressions(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Config based features can accept regular expressions", "  Feature \"feature5\" is enabled only if the company\r\n  starts with \"abc\"", exampleTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 57
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table3.AddRow(new string[] {
                        "company",
                        string.Format("{0}", value)});
#line 58
  testRunner.And("the context contains", ((string)(null)), table3, "And ");
#line 61
  testRunner.Then(string.Format("feature \"feature5\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple values including regular expressions")]
        [NUnit.Framework.TestCaseAttribute("abc", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("abcdef", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("defabc", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("ZZZ", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("xyz", "disabled", null)]
        public virtual void MultipleValuesIncludingRegularExpressions(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple values including regular expressions", "  Feature \"feature6\" is enabled only if the company\r\n  starts with \"abc\" OR\r\n  en" +
                    "ds with \"abc\" OR\r\n  is \"ZZZ\"", exampleTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 76
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table4.AddRow(new string[] {
                        "company",
                        string.Format("{0}", value)});
#line 77
  testRunner.And("the context contains", ((string)(null)), table4, "And ");
#line 80
  testRunner.Then(string.Format("feature \"feature6\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Config based features can accept comparisons")]
        [NUnit.Framework.TestCaseAttribute("26", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("27", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("28", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("29", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("30", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("31", "enabled", null)]
        public virtual void ConfigBasedFeaturesCanAcceptComparisons(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Config based features can accept comparisons", "  Feature \"feature7\" is enabled only if the price is\r\n  less than 27 OR\r\n  greate" +
                    "r than or equal to 30", exampleTags);
#line 90
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 96
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table5.AddRow(new string[] {
                        "price",
                        string.Format("{0}", value)});
#line 97
  testRunner.And("the context contains", ((string)(null)), table5, "And ");
#line 100
  testRunner.Then(string.Format("feature \"feature7\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Config based features can accept compound comparisons")]
        [NUnit.Framework.TestCaseAttribute("17", "disabled", null)]
        [NUnit.Framework.TestCaseAttribute("18", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("19", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("20", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("21", "enabled", null)]
        [NUnit.Framework.TestCaseAttribute("22", "disabled", null)]
        public virtual void ConfigBasedFeaturesCanAcceptCompoundComparisons(string value, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Config based features can accept compound comparisons", "  Feature \"feature8\" is enabled only if the price is\r\n  greater than 17 AND\r\n  le" +
                    "ss than or equal to 21", exampleTags);
#line 111
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 117
  testRunner.Given("features are defined in a config file \"settings.json\" under prefix \"features\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table6.AddRow(new string[] {
                        "price",
                        string.Format("{0}", value)});
#line 118
  testRunner.And("the context contains", ((string)(null)), table6, "And ");
#line 121
  testRunner.Then(string.Format("feature \"feature8\" is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
